# Generated by Django 3.2.15 on 2022-10-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
